name       : postgresql
version    : 9.6.6
release    : 17
source     :
    - http://ftp.postgresql.org/pub/source/v9.6.6/postgresql-9.6.6.tar.bz2 : 399cdffcb872f785ba67e25d275463d74521566318cfef8fe219050d063c8154
license    :
    - PostgreSQL
    - TCL
component  : database
optimize   : speed
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(python-2.7)
    - pam-devel
    - python-distutils-extra
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl \
         --with-systemd
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/postgresql.sysusers $installdir/%libdir%/sysusers.d/postgresql.conf
    install -D -m 00644 $pkgfiles/postgresql.tmpfiles $installdir/%libdir%/tmpfiles.d/postgresql.conf
    install -D -m 00644 $pkgfiles/postgresql.service $installdir/%libdir%/systemd/system/postgresql.service
    install -Dm 00755 $pkgfiles/postgresql_first_install $installdir/usr/share/postgresql/postgresql_first_install
