name       : postgresql
version    : 9.4.4
release    : 1
source     :
    - https://ftp.postgresql.org/pub/source/v9.4.4/postgresql-9.4.4.tar.bz2 : 538ed99688d6fdbec6fd166d1779cf4588bf2f16c52304e5ef29f904c43b0013
license    :  # See https://wiki.postgresql.org/wiki/FAQ#What_is_the_license_of_PostgreSQL.3F
  - Portions Copyright (c) 1996-2011, PostgreSQL Global Development Group
  - Portions Copyright (c) 1994, The Regents of the University of California
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
  - pkgconfig(libxml-2.0)
  - pkgconfig(openssl)
  - pkgconfig(python)
  - pkgconfig(zlib)
  - readline
  - pam
  - python-distutils-extra
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml
build      : |
    %make
install    : |
    %make_install
    make clean
