name       : postgresql
version    : 9.5.5
release    : 10
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.5/postgresql-9.5.5.tar.bz2 : 02c65290be74de6604c3fed87c9fd3e6b32e949f0ab8105a75bd7ed5aa71f394
license    :
    - PostgreSQL
    - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(zlib)
    - pam-devel
    - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
