name       : postgresql
version    : 9.5.6
release    : 11
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.6/postgresql-9.5.6.tar.bz2 : bb9e5f6d34e20783e96e10c1d6c0c09c31749e802aaa46b793ce2522725ae12f
license    :
    - PostgreSQL
    - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(zlib)
    - pam-devel
    - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
