name       : postgresql
version    : 9.6.2
release    : 12
source     :
    - http://ftp.postgresql.org/pub/source/v9.6.2/postgresql-9.6.2.tar.bz2 : 0187b5184be1c09034e74e44761505e52357248451b0c854dddec6c231fe50c9
license    :
    - PostgreSQL
    - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(zlib)
    - pam-devel
    - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
