name       : postgresql
version    : 9.5.4
release    : 9
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.4/postgresql-9.5.4.tar.bz2 : cf5e571164ad66028ecd7dd8819e3765470d45bcd440d258b686be7e69c76ed0
license    :
    - PostgreSQL
    - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(zlib)
    - pam-devel
    - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
