name       : postgresql
version    : '15.1'
release    : 38
homepage   : https://www.postgresql.org/
source     :
    - https://ftp.postgresql.org/pub/source/v15.1/postgresql-15.1.tar.gz : ea2cf059a85882654b989acd07edc121833164a30340faee0d3615cf7058e66c
license    :
    - PostgreSQL
    - TCL
component  :
    - database
    - libpq   : programming.library
    - contrib : database
optimize   : speed
summary    :
    - PostgreSQL is an object-relational database system
    - libpq   : PostgreSQL C client library
    - contrib : Extension modules distributed with PostgreSQL
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
patterns   :
    - libpq :
        - /usr/lib64/libpq.so.*
    - contrib :
        - /usr/lib64/postgresql/_int.so
        - /usr/lib64/postgresql/adminpack.so
        - /usr/lib64/postgresql/amcheck.so
        - /usr/lib64/postgresql/auth_delay.so
        - /usr/lib64/postgresql/auto_explain.so
        - /usr/lib64/postgresql/autoinc.so
        - /usr/lib64/postgresql/bloom.so
        - /usr/lib64/postgresql/btree_gin.so
        - /usr/lib64/postgresql/btree_gist.so
        - /usr/lib64/postgresql/chkpass.so
        - /usr/lib64/postgresql/citext.so
        - /usr/lib64/postgresql/cube.so
        - /usr/lib64/postgresql/dblink.so
        - /usr/lib64/postgresql/dict_int.so
        - /usr/lib64/postgresql/dict_xsyn.so
        - /usr/lib64/postgresql/earthdistance.so
        - /usr/lib64/postgresql/file_fdw.so
        - /usr/lib64/postgresql/fuzzystrmatch.so
        - /usr/lib64/postgresql/hstore.so
        - /usr/lib64/postgresql/hstore_plpython3.so
        - /usr/lib64/postgresql/insert_username.so
        - /usr/lib64/postgresql/isn.so
        - /usr/lib64/postgresql/lo.so
        - /usr/lib64/postgresql/ltree.so
        - /usr/lib64/postgresql/ltree_plpython3.so
        - /usr/lib64/postgresql/moddatetime.so
        - /usr/lib64/postgresql/pageinspect.so
        - /usr/lib64/postgresql/passwordcheck.so
        - /usr/lib64/postgresql/pg_buffercache.so
        - /usr/lib64/postgresql/pg_freespacemap.so
        - /usr/lib64/postgresql/pg_prewarm.so
        - /usr/lib64/postgresql/pg_stat_statements.so
        - /usr/lib64/postgresql/pg_trgm.so
        - /usr/lib64/postgresql/pg_visibility.so
        - /usr/lib64/postgresql/pgcrypto.so
        - /usr/lib64/postgresql/pgrowlocks.so
        - /usr/lib64/postgresql/pgstattuple.so
        - /usr/lib64/postgresql/pgxml.so
        - /usr/lib64/postgresql/postgres_fdw.so
        - /usr/lib64/postgresql/refint.so
        - /usr/lib64/postgresql/seg.so
        - /usr/lib64/postgresql/sslinfo.so
        - /usr/lib64/postgresql/tablefunc.so
        - /usr/lib64/postgresql/tcn.so
        - /usr/lib64/postgresql/test_decoding.so
        - /usr/lib64/postgresql/timetravel.so
        - /usr/lib64/postgresql/tsm_system_rows.so
        - /usr/lib64/postgresql/tsm_system_time.so
        - /usr/lib64/postgresql/unaccent.so
builddeps  :
    - pkgconfig(libcrypt)
    - pkgconfig(python3)
    - python-distutils-extra
setup      : |
    %configure --bindir=/usr/bin --disable-static \
        --with-pam \
        --with-python \
        --with-libxml \
        --with-openssl \
        --with-systemd \
        --with-system-tzdata=/usr/share/zoneinfo \
        --with-uuid=e2fs \
        PYTHON=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
    %make_install -C contrib
    install -Dm 00644 $pkgfiles/postgresql.sysusers $installdir/%libdir%/sysusers.d/postgresql.conf
    install -Dm 00644 $pkgfiles/postgresql.tmpfiles $installdir/%libdir%/tmpfiles.d/postgresql.conf
    install -Dm 00644 $pkgfiles/postgresql.service $installdir/%libdir%/systemd/system/postgresql.service
    install -Dm 00755 $pkgfiles/postgresql_first_install $installdir/usr/share/postgresql/postgresql_first_install
