name       : postgresql
version    : 9.6.4
release    : 14
source     :
    - http://ftp.postgresql.org/pub/source/v9.6.4/postgresql-9.6.4.tar.bz2 : 2b3ab16d82e21cead54c08b95ce3ac480696944a68603b6c11b3205b7376ce13
license    :
    - PostgreSQL
    - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(zlib)
    - pam-devel
    - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl \
         --with-systemd
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/postgresql.sysusers $installdir/%libdir%/sysusers.d/postgresql.conf
    install -D -m 00644 $pkgfiles/postgresql.tmpfiles $installdir/%libdir%/tmpfiles.d/postgresql.conf
    install -D -m 00644 $pkgfiles/postgresql.service $installdir/%libdir%/systemd/system/postgresql.service
    install -Dm 00755 $pkgfiles/postgresql_first_install $installdir/usr/share/postgresql/postgresql_first_install
