name       : postgresql
version    : 9.5.3
release    : 8
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.3/postgresql-9.5.3.tar.bz2 : 7385c01dc58acba8d7ac4e6ad42782bd7c0b59272862a3a3d5fe378d4503a0b4
license    :
  - PostgreSQL
  - TCL
component  : database
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
  - pkgconfig(libxml-2.0)
  - pkgconfig(openssl)
  - pkgconfig(python-2.7)
  - pkgconfig(zlib)
  - pam-devel
  - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
