name       : postgresql
version    : 9.5.2
release    : 7
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.2/postgresql-9.5.2.tar.bz2 : f8d132e464506b551ef498719f18cfe9d777709c7a1589dc360afc0b20e47c41
license    :
  - PostgreSQL
  - TCL
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
  - pkgconfig(libxml-2.0)
  - pkgconfig(openssl)
  - pkgconfig(python-2.7)
  - pkgconfig(zlib)
  - pam-devel
  - python-distutils-extra
optimize   : speed
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml \
         --with-openssl
build      : |
    %make
install    : |
    %make_install
