name       : postgresql
version    : 9.5.1
release    : 5
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.1/postgresql-9.5.1.tar.bz2 : 6b309d8506a39773a752ff074f47656e5424576ea090b04a24fe1725958c5bd2
license    :
  - PostgreSQL
  - TCL
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
  - pkgconfig(libxml-2.0)
  - pkgconfig(openssl)
  - pkgconfig(python-2.7)
  - pkgconfig(zlib)
  - readline
  - pam
  - python-distutils-extra
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml
build      : |
    %make
install    : |
    %make_install
    make clean
