name       : postgresql
version    : 9.5.0
release    : 4
source     :
    - https://ftp.postgresql.org/pub/source/v9.5.0/postgresql-9.5.0.tar.bz2 : f1c0d3a1a8aa8c92738cab0153fbfffcc4d4158b3fee84f7aa6bfea8283978bc
license    :
  - PostgreSQL
  - TCL
summary    : PostgreSQL is an object-relational database system.
description: |
    PostgreSQL is an object-relational database system that has the features of traditional proprietary database systems with enhancements to be found in next-generation DBMS systems.
builddeps  :
  - pkgconfig(libxml-2.0)
  - pkgconfig(openssl)
  - pkgconfig(python-2.7)
  - pkgconfig(zlib)
  - readline
  - pam
  - python-distutils-extra
setup      : |
    %configure --bindir=/usr/bin --disable-static \
         --with-pam \
         --with-python \
         --with-libxml
build      : |
    %make
install    : |
    %make_install
    make clean
